### ISSUE TITLE
Session Id

### ISSUE THREAD

**Issue by Elblassy** [divad1196/odoo_nginx_proxy#1]
how can i read session id from header when authenticate if i use ( * ) as origin

**Comment by divad1196** [comment]
Hi and thanks for the question

> how can i read session id from header when authenticate if i use ( * ) as origin 

You need to add the following option on fetch command when doing cross-origin fetch to keep and use cookies:
```javascript
credentials: 'include'
```
But still, the cookie is http-only so unreadable. Take a look at the response of the query at `/web/session/authenticate`, there is many information in it, like the session_id if needed elsewhere than in a cookie. 

Finally, I recommend you not to use the wildcard '*' on production environment but only for development purpose. You could also use the nginx variable $http_origin instead of the wildcard. This way it won't appear as a wildcard but as if the origin that mades the query was the one supposed to.I still not recommend it for production.

**Comment by Elblassy** [comment]
Thank you for your replay 

i use this in nginx

```
location / {
		proxy_pass http://207.180.203.218:8069/;

        proxy_set_header Origin 'http://127.0.0.1:5500';

        proxy_hide_header Access-Control-Allow-Origin;
        add_header Access-Control-Allow-Origin 'http://127.0.0.1:5500' always;
        add_header Access-Control-Allow-Methods 'POST, GET' always;
        add_header 'Access-Control-Allow-Credentials' 'true' always;
        add_header Access-Control-Max-Age: 86400 always;  # 60 * 60 * 24;
        add_header Access-Control-Allow-Headers: 'Set-Cookie,session_id,Origin, X-Requested-With, Content-Type, Accept, Authorization, X-Debug-Mode' always;

        if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Allow-Origin' 'http://127.0.0.1:5500';
            add_header 'Access-Control-Allow-Methods' 'POST, GET' always;
            add_header 'Access-Control-Allow-Credentials' 'true' always;
        	add_header Access-Control-Allow-Headers: 'Set-Cookie,session_id,Origin, X-Requested-With, Content-Type, Accept, Authorization, X-Debug-Mode' always;
            add_header 'Access-Control-Max-Age' 86400;
            add_header 'Content-Type' 'text/plain; charset=utf-8';
            add_header 'Content-Length' 0;
            return 204;
        }
	
}
```

but i didn't get cookies also and i don't find session_id in response of auth as you say

**Comment by divad1196** [comment]
@Elblassy how are you doing your request? Can you show me the code you use?

**Comment by Elblassy** [comment]
```
 headers = new Headers({
                'Content-Type': 'application/json'
            });
            parameters = {
                method: 'POST',
                headers: headers,
                mode: 'cors',
                cache: 'default',
                body: JSON.stringify({
                    "id": 1640273333979,
                    "jsonrpc": "2.0",
                    "method": "call",
                    "params": {
                        "db": "sale",
                        "login": "demo@sst-egy.com",
                        "password": "123456",
                        "context": {}
                    }
                })
            };
            var res = await fetch("https://sst-egy.com" + "/web/session/authenticate", parameters);
            console.log(res.headers.get("Set-Cookie"));
```

i run it from my pc (localhost) and odoo on other server , should i make two of them has same domain with change in subdomain ? i am mobile developer so i don't know much in web 😕

**Comment by divad1196** [comment]
@Elblassy 
As told, you won't get anything from the headers, the cookies are protected.
![image](https://user-images.githubusercontent.com/43037556/151124700-23b17a34-6d4d-4f05-9d44-4f6c6bdf2542.png)

If you use `credentials: 'include'` option, the cookie will automatically be saved and used then. You don't even need the query's result for the cookie to be saved if using this option. If you still want the result of the response, you must do so: `var data = await fetch(url, parameters).then(r => r.json());`.

I just tested for V14, and the body of the response does not contains the session_id entry anymore, and I think this is a good think for security issue. Do you have any reason to manage the session_id yourself?

**Comment by Elblassy** [comment]
I am using flutter to build front-end app (mobile & web) connected with odoo if i use one domain in origin it won't work in mobile , so i go to make my custom REST API connected and call odoo request then call it api from my front-end 😅thank you for your time 🙏🏻

**Comment by divad1196** [comment]
@Elblassy I don't get the following part
> if i use one domain in origin it won't work in mobile

"one" as "only one" or did you meant "a domain"?

I think there are plenty of misunderstanding here. 
What ever you are trying to do, you will need those options on `fetch` to do cross-origin queries with cookies on a navigator. There is certainly a way in flutter to have cross-origin queries work seamlessly on both web and mobile, but you would need to search for it yourself. I may try it myself one-day using flutter and add it to the doc, but not in the near future.

For security issue, I would recommend you to stick to the cookie and not keeping anything to connect (as credential or token) within the javascript code.
And a bit of self-advertising: If you need an api (not for authentication but for queries), you can use a graphql api https://apps.odoo.com/apps/modules/15.0/odoo_graphql/

Have a nice day and good luck for the rest.

**Comment by Elblassy** [comment]
the part you misunderstood : i mean if i specify domain in access origin so i can't call odoo any where unless this domain so i can't use it in mobile as i know.

i will try this module.

thank you for your time and i am happy to discuss my problem with you 😃

**Comment by Elblassy** [comment]
I want to tell you it worked for me ! 

i set origin to sub domain of domain that connected to my odoo server and it work in web and mobile !
thank you very much 😄
